export const jobApplicants = [
	{
		id: '420a15b25206c1687068097349',
		date: '2023-05-15',
		recruiterName: 'John Doe',
		clientName: 'ABC Corporation',
		candidateName: 'Jane Smith',
		currentCompany: 'ABC Corporation',
		currentPosition: 'Software Engineer',
		currentJobLocation: 'New York',
		contactNo: '1234567890',
		email: 'johndoe@example.com',
		qualification: "Bachelor's Degree",
		experience: '3',
		relevantExperience: '2',
		currentCtc: '8',
		expectedCtc: '10',
		noticePeriod: 'Yes',
		noticePeriodDate: '2023-06-15',
		holdingOffer: 'No',
		holdingOfferCtc: '',
		reason: 'Looking for career growth',
		remark: 'N/A',
	},
	{
		id: 'a2524ce4286841687068097349',
		date: '2023-05-14',
		recruiterName: 'Emily Johnson',
		clientName: 'XYZ Corporation',
		candidateName: 'Michael Brown',
		currentCompany: 'XYZ Corporation',
		currentPosition: 'Sales Manager',
		currentJobLocation: 'San Francisco',
		contactNo: '9876543210',
		email: 'emilyjohnson@example.com',
		qualification: "Master's Degree",
		experience: '5',
		relevantExperience: '3',
		currentCtc: '12',
		expectedCtc: '15',
		noticePeriod: 'No',
		noticePeriodDate: '',
		holdingOffer: 'Yes',
		holdingOfferCtc: '18',
		reason: 'Better job opportunity',
		remark: 'Prefers remote work',
	},
	{
		id: '79ce03332c54c1687068097349',
		date: '2023-05-16',
		recruiterName: 'Sarah Thompson',
		clientName: 'XYZ Corporation',
		candidateName: 'Robert Johnson',
		currentCompany: 'XYZ Corporation',
		currentPosition: 'Software Developer',
		currentJobLocation: 'Seattle',
		contactNo: '5551234567',
		email: 'robertjohnson@example.com',
		qualification: "Bachelor's Degree",
		experience: '4',
		relevantExperience: '3',
		currentCtc: '9',
		expectedCtc: '11',
		noticePeriod: 'Yes',
		noticePeriodDate: '2023-07-01',
		holdingOffer: 'No',
		holdingOfferCtc: '',
		reason: 'Seeking new challenges',
		remark: '',
	},
	{
		id: '2589fdfc2bbff1687068097349',
		date: '2023-05-17',
		recruiterName: 'Michael Williams',
		clientName: 'PQR Industries',
		candidateName: 'Amy Davis',
		currentCompany: 'PQR Industries',
		currentPosition: 'Marketing Specialist',
		currentJobLocation: 'Chicago',
		contactNo: '5559876543',
		email: 'amydavis@example.com',
		qualification: "Bachelor's Degree",
		experience: '2',
		relevantExperience: '1',
		currentCtc: '6',
		expectedCtc: '8',
		noticePeriod: 'Yes',
		noticePeriodDate: '2023-06-30',
		holdingOffer: 'No',
		holdingOfferCtc: '',
		reason: 'Relocation',
		remark: '',
	},
	{
		id: 'a9c5e543d147e1687068097349',
		date: '2023-05-18',
		recruiterName: 'David Brown',
		clientName: 'LMN Corporation',
		candidateName: 'Jennifer Wilson',
		currentCompany: 'LMN Corporation',
		currentPosition: 'Project Manager',
		currentJobLocation: 'Austin',
		contactNo: '5554567890',
		email: 'jenniferwilson@example.com',
		qualification: "Master's Degree",
		experience: '7',
		relevantExperience: '5',
		currentCtc: '15',
		expectedCtc: '18',
		noticePeriod: 'No',
		noticePeriodDate: '',
		holdingOffer: 'Yes',
		holdingOfferCtc: '20',
		reason: 'Advancement opportunities',
		remark: '',
	},
	{
		id: '3281d551896a31687068097349',
		date: '2023-05-19',
		recruiterName: 'Emily Johnson',
		clientName: 'XYZ Corporation',
		candidateName: 'Daniel Smith',
		currentCompany: 'XYZ Corporation',
		currentPosition: 'Software Engineer',
		currentJobLocation: 'San Francisco',
		contactNo: '5552345678',
		email: 'danielsmith@example.com',
		qualification: "Bachelor's Degree",
		experience: '4',
		relevantExperience: '3',
		currentCtc: '10',
		expectedCtc: '12',
		noticePeriod: 'Yes',
		noticePeriodDate: '2023-06-30',
		holdingOffer: 'No',
		holdingOfferCtc: '',
		reason: 'Career growth',
		remark: '',
	},
	{
		id: 'fbd9b2b1262d51687068097349',
		date: '2023-05-20',
		recruiterName: 'John Doe',
		clientName: 'ABC Corporation',
		candidateName: 'Michelle Johnson',
		currentCompany: 'ABC Corporation',
		currentPosition: 'Marketing Manager',
		currentJobLocation: 'New York',
		contactNo: '5558765432',
		email: 'michellejohnson@example.com',
		qualification: "Master's Degree",
		experience: '6',
		relevantExperience: '4',
		currentCtc: '14',
		expectedCtc: '16',
		noticePeriod: 'No',
		noticePeriodDate: '',
		holdingOffer: 'Yes',
		holdingOfferCtc: '18',
		reason: 'New challenges',
		remark: 'Prefers flexible work hours',
	},
	{
		id: '1a28b5e9b3d231687068097349',
		date: '2023-05-21',
		recruiterName: 'Sarah Thompson',
		clientName: 'PQR Industries',
		candidateName: 'David Wilson',
		currentCompany: 'PQR Industries',
		currentPosition: 'Software Developer',
		currentJobLocation: 'Seattle',
		contactNo: '5557654321',
		email: 'davidwilson@example.com',
		qualification: "Bachelor's Degree",
		experience: '3',
		relevantExperience: '2',
		currentCtc: '9',
		expectedCtc: '11',
		noticePeriod: 'Yes',
		noticePeriodDate: '2023-07-01',
		holdingOffer: 'No',
		holdingOfferCtc: '',
		reason: 'Better job opportunity',
		remark: '',
	},
	{
		id: 'cbe1d3d345a2b1687068097349',
		date: '2023-05-22',
		recruiterName: 'Michael Williams',
		clientName: 'LMN Corporation',
		candidateName: 'Olivia Davis',
		currentCompany: 'LMN Corporation',
		currentPosition: 'Business Analyst',
		currentJobLocation: 'Austin',
		contactNo: '5556543210',
		email: 'oliviadavis@example.com',
		qualification: "Master's Degree",
		experience: '5',
		relevantExperience: '4',
		currentCtc: '12',
		expectedCtc: '14',
		noticePeriod: 'Yes',
		noticePeriodDate: '2023-06-15',
		holdingOffer: 'No',
		holdingOfferCtc: '',
		reason: 'Career advancement',
		remark: '',
	},
	{
		id: '749c1d5519b271687068097349',
		date: '2023-05-23',
		recruiterName: 'David Brown',
		clientName: 'XYZ Corporation',
		candidateName: 'Sophia Johnson',
		currentCompany: 'XYZ Corporation',
		currentPosition: 'Product Manager',
		currentJobLocation: 'San Francisco',
		contactNo: '5555432167',
		email: 'sophiajohnson@example.com',
		qualification: "Bachelor's Degree",
		experience: '7',
		relevantExperience: '5',
		currentCtc: '16',
		expectedCtc: '19',
		noticePeriod: 'No',
		noticePeriodDate: '',
		holdingOffer: 'Yes',
		holdingOfferCtc: '22',
		reason: 'New challenges',
		remark: 'Willing to relocate',
	},
];

export const clientCredentials = [
	{
		username: 'ABC Corporation',
		password: '7x4izk3y',
	},
	{
		username: 'XYZ Corporation',
		password: '2o9emc7g',
	},
	{
		username: 'PQR Industries',
		password: '6j8ql41x',
	},
	{
		username: 'LMN Corporation',
		password: '9t5klpvg',
	},
];

export const recruiterCredentials = [
	{
		username: 'John Doe',
		password: 'YlYa8diw',
	},
	{
		username: 'Emily Johnson',
		password: '7qVOLwdB',
	},
	{
		username: 'Sarah Thompson',
		password: 'YNlXptem',
	},
	{
		username: 'Michael Williams',
		password: 'UrCaQ9jt',
	},
	{
		username: 'David Brown',
		password: '7bg35mCp',
	},
	{
		username: 'Emily Johnson',
		password: '8ykQq12E',
	},
	{
		username: 'John Doe',
		password: 'L52SlSQJ',
	},
	{
		username: 'Sarah Thompson',
		password: 'Nno16mJ0',
	},
	{
		username: 'Michael Williams',
		password: 'LAbhosc4',
	},
	{
		username: 'David Brown',
		password: 'vMfNZPRy',
	},
];

export const managerCredientals = [
	{
		username: 'manager',
		password: 'vMfNZPRyt892',
	},
];

// localStorage.setItem('jobApplicants', JSON.stringify(jobApplicants));
// localStorage.setItem('clientCredentials', JSON.stringify(clientCredentials));
// localStorage.setItem(
// 	'recruiterCredentials',
// 	JSON.stringify(recruiterCredentials)
// );
// localStorage.setItem('managerCredientals', JSON.stringify(managerCredientals));
